name: schedule
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0"

dependencies:
  shared_preferences: ^0.4.3
  sqflite: ^1.0.0
  path_provider: ^0.4.1
  intl: ^0.15.7
  intl_translation: ^0.17.0
  
  flutter:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"

flutter:

  uses-material-design: true
  assets:
    - assets/data.db