name: schedule

version: 1.0.0+1

environment:
  sdk: ">=2.1.0"

dependencies:
  shared_preferences: ^0.5.3+2
  sqflite: ^1.0.0
  intl: ^0.15.7
  intl_translation: ^0.17.0
  flutter_bloc: ^0.20.1
  equatable: ^0.4.0
  meta: ^1.1.6
  dio: ^2.1.0
  parse_server_sdk: ^1.0.24

  flutter:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"

flutter:

  uses-material-design: true
  assets:
    - assets/data.db